server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Return index.html for all routes so React Router can handle them
        try_files $uri $uri/ /index.html;
    }
}
